# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ci9yvlp5ezDfNvPzhNBCST3GyuQ_MTDj
"""

!pip install torch torchvision torchaudio
!pip install torch-geometric

# PyTorch Geometric dependencies
!pip install pyg_lib torch_scatter torch_sparse torch_cluster torch_spline_conv -f https://data.pyg.org/whl/torch-2.1.0+cpu.html
!pip install torch-geometric

import torch
from torch_geometric.datasets import Planetoid
from torch_geometric.transforms import NormalizeFeatures

# تحميل بيانات Cora مع تطبيع الخصائص
dataset = Planetoid(root='data/Planetoid', name='Cora', transform=NormalizeFeatures())
data = dataset[0]  # لأن Cora تحتوي على رسم بياني واحد فقط

import torch.nn.functional as F
from torch_geometric.nn import GATConv
import torch.nn as nn

class GATNet(torch.nn.Module):
    def __init__(self, in_channels, hidden_channels, out_channels, heads=8):
        super(GATNet, self).__init__()

        self.gat1 = GATConv(in_channels, hidden_channels, heads=heads, dropout=0.6)

        self.gat2 = GATConv(hidden_channels * heads, out_channels, heads=1, concat=False, dropout=0.6)


    def forward(self, x, edge_index):
        x = self.gat1(x, edge_index)
        x = F.elu(x)
        x = F.dropout(x, p=0.6, training=self.training)
        x = self.gat2(x, edge_index)
        return F.log_softmax(x, dim=1)

def train(model, data, optimizer, criterion, epochs=200):
    model.train()
    for epoch in range(1, epochs+1):
        optimizer.zero_grad()
        out = model(data.x, data.edge_index)
        loss = criterion(out[data.train_mask], data.y[data.train_mask])
        loss.backward()
        optimizer.step()

        if epoch % 10 == 0:
            val_acc = evaluate(model, data, mask=data.val_mask)
            print(f"Epoch {epoch:03d}, Loss: {loss:.4f}, Val Acc: {val_acc:.4f}")

def evaluate(model, data, mask):
    model.eval()
    with torch.no_grad():
        out = model(data.x, data.edge_index)
        pred = out[mask].argmax(dim=1)
        correct = pred.eq(data.y[mask]).sum().item()
        acc = correct / mask.sum().item()
    return acc

def test(model, data):
    test_acc = evaluate(model, data, mask=data.test_mask)
    print(f"Test Accuracy: {test_acc:.4f}")

model = GATNet(dataset.num_node_features, hidden_channels=8, out_channels=dataset.num_classes)
optimizer = torch.optim.Adam(model.parameters(), lr=0.005, weight_decay=5e-4)
criterion = torch.nn.CrossEntropyLoss()

train(model, data, optimizer, criterion)
test(model, data)

from torch_geometric.nn import GCNConv

class GCNNet(torch.nn.Module):
    def __init__(self, in_channels, hidden_channels, out_channels):
        super(GCNNet, self).__init__()
        self.conv1 = GCNConv(in_channels, hidden_channels)
        self.conv2 = GCNConv(hidden_channels, out_channels)

    def forward(self, x, edge_index):
        x = self.conv1(x, edge_index)
        x = F.relu(x)
        x = F.dropout(x, p=0.5, training=self.training)
        x = self.conv2(x, edge_index)
        return F.log_softmax(x, dim=1)